# Generated by Django 5.0 on 2023-12-23 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurancemanagement', '0006_policyrecord_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policyapply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Pending', max_length=100)),
                ('creation_date', models.DateField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurancemanagement.user')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurancemanagement.policy')),
            ],
        ),
    ]
